[package]
name = "ssocca"
version = "0.4.0"
edition = "2021"
license = "MIT"
authors = ["Atsushi KAWASAKI <ak@xlix.org>"]
description = "SSO Credential Cookie Acquirer"

[dependencies]
anyhow = "1.0.68"
chromiumoxide = { version = "0.4.0", features = [
    "tokio-runtime",
], default-features = false }
clap = { version = "4.1.1", features = ["derive"] }
futures = "0.3.25"
headless_chrome = { git = "https://github.com/atroche/rust-headless-chrome", rev = "4e91d90edee71112ee3729c4a99e3bf0e1a06cbb" }
tokio = { version = "1.24.2", features = ["full"] }

[dev-dependencies]
rstest = "0.16.0"
