name: Check and Test

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.70.0
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
  clippy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.70.0
          components: clippy
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    runs-on: ubuntu-latest
    needs: [check, clippy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.70.0
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
